spring.datasource.url=jdbc:postgresql://prod-db-host:5432/library_prod
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false
spring.liquibase.contexts=prod
